"""
Evaluate original or finetuned Qwen model for entity extraction format accuracy.

USAGE:
    python evaluate.py --model_size 4B --dataset text_to_correct_200_dev.json
    python evaluate.py --model_size 8B --lora_path finetuned-8B-200-lora --use_lora --dataset text_to_correct_200_dev.json

Arguments:
    --model_size   : '4B' or '8B' (default: 4B). Determines which base model path to use (from .env).
    --lora_path    : Path to the LoRA adapter or finetuned model directory. Required if --use_lora is set.
    --use_lora     : If set, loads the LoRA adapter for evaluation. Otherwise, evaluates the base model.
    --dataset      : Path to the evaluation dataset (JSON). Required.

Environment:
    Requires .env file with PATH_QWEN_4B and PATH_QWEN_8B variables set to the local model paths.

Outputs:
    - Saves detailed predictions and labels to ./eval_outputs/
    - Saves a summary of evaluation results to ./evaluation_summary/

Example:
    python evaluate.py --model_size 4B --lora_path finetuned-4B-200-lora --use_lora --dataset text_to_correct_200_dev.json
    python evaluate.py --model_size 8B --dataset text_to_correct_800_dev.json
"""
# Evaluate original/finetuned model.
# Perform entity extraction with original LightRAG prompts,
# check the correctness of the format of extraction outputs,
# and calculate the ratio of correctly formatted responses.
#
# Depend on the datasets generated by `generate_long_text_entites_dataset.py`.


import torch
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
from datasets import load_dataset
from peft import PeftModel
import os
import json
from datetime import datetime
from tqdm import tqdm
import re
import argparse

from prompt import PROMPTS

from dotenv import load_dotenv

# Borrowed from LightRAG
def fix_tuple_delimiter_corruption(
    record: str, 
    delimiter_core="#", 
    tuple_delimiter="<|#|>"
) -> str:
    """
    Fix various forms of tuple_delimiter corruption from LLM output.

    This function handles missing or replaced characters around the core delimiter.
    It fixes common corruption patterns where the LLM output doesn't match the expected
    tuple_delimiter format.

    Args:
        record: The text record to fix
        delimiter_core: The core delimiter (e.g., "S" from "<|#|>")
        tuple_delimiter: The complete tuple delimiter (e.g., "<|#|>")

    Returns:
        The corrected record with proper tuple_delimiter format
    """
    if not record or not delimiter_core or not tuple_delimiter:
        return record

    # Escape the delimiter core for regex use
    escaped_delimiter_core = re.escape(delimiter_core)

    # Fix: <|##|> -> <|#|>, <|#||#|> -> <|#|>, <|#|||#|> -> <|#|>
    record = re.sub(
        rf"<\|{escaped_delimiter_core}\|*?{escaped_delimiter_core}\|>",
        tuple_delimiter,
        record,
    )

    # Fix: <|\#|> -> <|#|>
    record = re.sub(
        rf"<\|\\{escaped_delimiter_core}\|>",
        tuple_delimiter,
        record,
    )

    # Fix: <|> -> <|#|>, <||> -> <|#|>
    record = re.sub(
        r"<\|+>",
        tuple_delimiter,
        record,
    )

    # Fix: <X|#|> -> <|#|>, <|#|Y> -> <|#|>, <X|#|Y> -> <|#|>, <||#||> -> <|#|>, <||#> -> <|#|> (one extra characters outside pipes)
    record = re.sub(
        rf"<.?\|{escaped_delimiter_core}\|*?>",
        tuple_delimiter,
        record,
    )

    # Fix: <#>, <#|>, <|#> -> <|#|> (missing one or both pipes)
    record = re.sub(
        rf"<\|?{escaped_delimiter_core}\|?>",
        tuple_delimiter,
        record,
    )

    # Fix: <X#|> -> <|#|>, <|#X> -> <|#|> (one pipe is replaced by other character)
    record = re.sub(
        rf"<[^|]{escaped_delimiter_core}\|>|<\|{escaped_delimiter_core}[^|]>",
        tuple_delimiter,
        record,
    )

    # Fix: <|#| -> <|#|>, <|#|| -> <|#|> (missing closing >)

    record = re.sub(
        rf"<\|{escaped_delimiter_core}\|+(?!>)",
        tuple_delimiter,
        record,
    )

    # Fix <|#: -> <|#|> (missing closing >)
    record = re.sub(
        rf"<\|{escaped_delimiter_core}:(?!>)",
        tuple_delimiter,
        record,
    )

    # Fix: <|| -> <|#|>
    record = re.sub(
        r"<\|\|(?!>)",
        tuple_delimiter,
        record,
    )

    # Fix: |#|> -> <|#|> (missing opening <)
    record = re.sub(
        rf"(?<!<)\|{escaped_delimiter_core}\|>",
        tuple_delimiter,
        record,
    )

    # Fix: <|#|>| -> <|#|>  ( this is a fix for: <|#|| -> <|#|> )
    record = re.sub(
        rf"<\|{escaped_delimiter_core}\|>\|",
        tuple_delimiter,
        record,
    )

    # Fix: ||#|| -> <|#|> (double pipes on both sides without angle brackets)
    record = re.sub(
        rf"\|\|{escaped_delimiter_core}\|\|",
        tuple_delimiter,
        record,
    )

    return record

def is_format_correct(response_text: str) -> bool:
    tuple_delimiter = PROMPTS["NEW_DEFAULT_TUPLE_DELIMITER"]
    completion_delimiter = PROMPTS["DEFAULT_COMPLETION_DELIMITER"]

    if not response_text.strip().endswith(completion_delimiter):
        return False
    
    main_content = response_text.strip().removesuffix(completion_delimiter).strip()
    if not main_content:
        return False
    records = main_content.split("\n")

    if not records:
        return False

    for record in records:
        record = fix_tuple_delimiter_corruption(record.strip())
        if not record: 
            continue
        num_delimiters = record.count(tuple_delimiter)
        if record.startswith('entity'):
            if num_delimiters != 3: return False
        elif record.startswith('relation'):
            if num_delimiters != 4: return False
        elif num_delimiters > 0:
            return False
            
    return True

def evaluate(local_model_path, finetuned_lora_path, use_lora, eval_dataset_path):
    # Load model and tokenizer
    print("Loading model...")
    base_model = AutoModelForCausalLM.from_pretrained(
        local_model_path, 
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 8 else torch.float16,
        device_map="auto",
        local_files_only=True
    )
    tokenizer = AutoTokenizer.from_pretrained(finetuned_lora_path)
    
    if use_lora:
        model = PeftModel.from_pretrained(base_model, finetuned_lora_path)
        model = model.merge_and_unload()
    else:
        model = base_model

    model.eval()

    # Load and prepare dataset
    print("Loading dataset...")
    try:
        raw_datasets = load_dataset("json", data_files={"dev": eval_dataset_path})
        eval_dataset = raw_datasets["dev"]
        print(f"Evaluating on {len(eval_dataset)} samples.")
    except Exception as e:
        print(f"Error loading dataset: {e}")
        return

    system_prompt_template = PROMPTS["entity_extraction_system_prompt"]
    user_prompt_template = PROMPTS["entity_extraction_user_prompt"]

    all_predictions = []
    all_labels = []
    device = model.device

    # Run evaluation loop
    print("Evaluating...")
    generation_config = GenerationConfig(
        max_new_tokens=8192,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.7,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

    with torch.no_grad():
        for item in tqdm(eval_dataset, desc="Evaluating Samples"):
            # 1. Create the prompt for the single item
            system_prompt = system_prompt_template.format(
                language=PROMPTS["DEFAULT_LANGUAGE"],
                tuple_delimiter=PROMPTS["NEW_DEFAULT_TUPLE_DELIMITER"],
                completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                entity_types=["person", "organization", "location", "miscellaneous"],
                examples="\n".join(PROMPTS["new_entity_extraction_examples"]).format(
                    tuple_delimiter=PROMPTS["NEW_DEFAULT_TUPLE_DELIMITER"],
                    completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                ),
                input_text=item["sentence"]
            )
             
            user_prompt = user_prompt_template.format(
                completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                language=PROMPTS["DEFAULT_LANGUAGE"],
            )
        
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ]
            
            # Tokenize the single item
            inputs = tokenizer.apply_chat_template(
                messages,
                add_generation_prompt=True,
                return_tensors="pt",
                enable_thinking=False,
            ).to(device)

            # Generation
            outputs = model.generate(inputs, generation_config=generation_config)
            
            # Decode and process the response
            full_response = tokenizer.decode(outputs[0], skip_special_tokens=False)
            response_only = full_response.split("<|im_start|>assistant\n")[-1].replace("<|im_end|>", "").strip()
            
            all_predictions.append(response_only)
            all_labels.append(item["response"])

    # Save outputs
    output_dir = "./eval_outputs"
    os.makedirs(output_dir, exist_ok=True)
    output_filename = f"evaluation_results_batch_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.json"
    output_path = os.path.join(output_dir, output_filename)

    with open(output_path, "w") as f:
        results_to_save = [{"prediction": p, "label": l} for p, l in zip(all_predictions, all_labels)]
        json.dump(results_to_save, f, indent=4)
    print(f"Evaluation outputs saved to {output_path}")

    # Calculate and print format accuracy
    def remove_think_tags(text):
        # Remove <think>...</think>
        return re.sub(r'<think>.*?</think>\s*', '', text, flags=re.DOTALL).strip()

    format_correct_count = sum([
        1 for resp in all_predictions if is_format_correct(remove_think_tags(resp))
    ])
    format_accuracy = format_correct_count / len(all_predictions) if len(all_predictions) > 0 else 0
    print(f"\nFormat Accuracy on Eval Set: {format_accuracy:.4f}")

    return {
        "model_path": local_model_path,
        "lora_path": finetuned_lora_path,
        "use_lora": use_lora,
        "dataset": eval_dataset_path,
        "format_accuracy": format_accuracy
    }

def main():
    parser = argparse.ArgumentParser(description="Evaluate entity extraction format accuracy.")
    parser.add_argument('--model_size', type=str, choices=['4B', '8B'], default='4B', help='Model size: 4B/8B')
    parser.add_argument('--lora_path', type=str, default=None, help='Path to finetuned LoRA adapter')
    parser.add_argument('--use_lora', action='store_true', help='Whether to use LoRA adapter')
    parser.add_argument('--dataset', type=str, required=True, help='Path to evaluation dataset')
    args = parser.parse_args()

    load_dotenv(dotenv_path=".env", override=True)
    path_4B = os.getenv("PATH_QWEN_4B")
    path_8B = os.getenv("PATH_QWEN_8B")

    if args.model_size == '4B':
        model_path = path_4B
    else:
        model_path = path_8B

    lora_path = args.lora_path if args.lora_path is not None else ""
    use_lora = args.use_lora
    dataset_path = args.dataset

    all_results = []
    all_results.append(evaluate(model_path, lora_path, use_lora, dataset_path))

    

    # Summary of evaluation
    os.makedirs("./evaluation_summary", exist_ok=True)
    summary_filename = f"./evaluation_summary/evaluation_summary_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.json"
    with open(summary_filename, "w") as f:
        json.dump(all_results, f, indent=4)
    print(f"\nAll evaluation summaries have been saved to {summary_filename}")

if __name__ == "__main__":
    main()

