# Finetune strategy 1.
# Do entity extraction with original LightRAG prompts
# and train the model by next-token prediction.
# 
# Depend on the datasets generated by `generate_long_text_entites_dataset.py`.

from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, GenerationConfig
from datasets import Dataset, load_dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
import torch
import re
from transformers import EvalPrediction
from datetime import datetime
import os

from prompt import PROMPTS

from dotenv import load_dotenv

def finetune(model_name, local_model_path, target_token_count, batch_size):
    tokenizer = AutoTokenizer.from_pretrained(local_model_path)
    model = AutoModelForCausalLM.from_pretrained(
        local_model_path, 
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 8 else torch.float16,
    )

    # Set pad_token to eos_token if it's not set
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Generation config
    model.generation_config.max_new_tokens = 512
    model.generation_config.pad_token_id = tokenizer.pad_token_id
    model.generation_config.eos_token_id = tokenizer.eos_token_id

    # LoRA
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )
    model = get_peft_model(model, lora_config)
    
    model.enable_input_require_grads()
    
    model.print_trainable_parameters()

    # Load and tokenize dataset
    data_files = {"train": f"./long_text_datasettext_to_correct_{target_token_count}_train.json", "dev": f"./long_text_dataset/text_to_correct_{target_token_count}_dev.json"}
    raw_datasets = load_dataset("json", data_files=data_files)

    def tokenize_function(examples):
        # Create a batch of messages
        system_prompt_template = PROMPTS["entity_extraction_system_prompt"]
        user_prompt_template = PROMPTS["entity_extraction_user_prompt"]

        batch_messages = []
        for i in range(len(examples["sentence"])):
            system_prompt = system_prompt_template.format(
                language=PROMPTS["DEFAULT_LANGUAGE"],
                tuple_delimiter=PROMPTS["NEW_DEFAULT_TUPLE_DELIMITER"],
                completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                entity_types=["person", "organization", "location", "miscellaneous"],
                examples="\n".join(PROMPTS["new_entity_extraction_examples"]).format(
                    tuple_delimiter=PROMPTS["NEW_DEFAULT_TUPLE_DELIMITER"],
                    completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                ),
                input_text=examples["sentence"][i]
            )
            user_prompt = user_prompt_template.format(
                completion_delimiter=PROMPTS["DEFAULT_COMPLETION_DELIMITER"],
                language=PROMPTS["DEFAULT_LANGUAGE"],
            )

            assistant_response = examples["response"][i]

            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
                {"role": "assistant", "content": assistant_response}
            ]
            batch_messages.append(messages)

        # Apply chat template
        tokenized_outputs = [
            tokenizer.apply_chat_template(
                conversation,
                truncation=True, 
                padding=False,
                max_length=8192,
                add_generation_prompt=False,
                enable_thinking = False
            ) for conversation in batch_messages
        ]
        
        # Mask instructions
        modified_labels = []
        assistant_token_ids = tokenizer.encode("<|im_start|>assistant", add_special_tokens=False)
        newline_token = tokenizer.encode("\n", add_special_tokens=False)[0]
        for tokenized_seq in tokenized_outputs:
            assistant_start_index = -1
            for i in range(len(tokenized_seq) - len(assistant_token_ids)):
                if tokenized_seq[i:i + len(assistant_token_ids)] == assistant_token_ids:
                    try:
                        assistant_start_index = tokenized_seq.index(newline_token, i) + 1
                        break
                    except ValueError:
                        pass
            if assistant_start_index != -1:
                labels = [-100] * assistant_start_index + tokenized_seq[assistant_start_index:]
            else:
                labels = [-100] * len(tokenized_seq)
            modified_labels.append(labels)

        return {
            "input_ids": tokenized_outputs,
            "labels": modified_labels,
        }

    tokenized_datasets = raw_datasets.map(tokenize_function, batched=True, remove_columns=["sentence", "response"])

    # Data collator for padding
    from transformers import DataCollatorForSeq2Seq
    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        pad_to_multiple_of=8,
        label_pad_token_id=-100,
        return_tensors="pt"
    )

    # Create run name for TensorBoard
    run_name = f"{model_name}_{target_token_count}_{datetime.now().strftime('%m-%d_%H-%M-%S')}"
    logging_dir = os.path.join('./tf-logs', run_name)

    # Training arguments
    training_args = TrainingArguments(
        output_dir="./results",
        per_device_train_batch_size=batch_size,
        num_train_epochs=target_token_count/200,
        logging_dir=logging_dir,
        logging_steps=10,
        save_strategy="epoch", # Save at the end of each epoch
        learning_rate= 1e-5, #2e-4,
        fp16=torch.cuda.is_available(),
        report_to="tensorboard",
        gradient_checkpointing=True,
        group_by_length=True,
    )

    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["dev"],
        data_collator=data_collator,
    )

    # Train
    trainer.train()

    # Save Model
    trainer.save_model(f"./finetuned-{model_name}-{target_token_count}-lora")
    tokenizer.save_pretrained(f"./finetuned-{model_name}-{target_token_count}-lora")
    print(f"Model and tokenizer saved to ./finetuned-{model_name}-{target_token_count}-lora")

def main():
    load_dotenv(dotenv_path=".env", override=True)
    path_4B = os.getenv("PATH_QWEN_4B")
    path_8B = os.getenv("PATH_QWEN_8B")

    finetune("4B", path_4B, 200, 1)
    finetune("4B", path_4B, 400, 1)
    finetune("4B", path_4B, 800, 1)
    finetune("8B", path_8B, 200, 1)
    finetune("8B", path_8B, 400, 1)
    finetune("8B", path_8B, 800, 1)

if __name__ == "__main__":
    main()
