# Finetune strategy 2.
# Directly train the model with (extraction output with wrong format, with correct format) pairs.
#
# Depend on the datasets generated by `generate_incorrect_correct_dataset.py`.
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
import torch
from datetime import datetime
import os
from prompt import PROMPTS

from dotenv import load_dotenv

def finetune_format_error(model_name, local_model_path, error_dataset_path, batch_size=2, max_length=2048):
    tokenizer = AutoTokenizer.from_pretrained(local_model_path)
    model = AutoModelForCausalLM.from_pretrained(
        local_model_path, 
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 8 else torch.float16,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )
    model = get_peft_model(model, lora_config)
    if hasattr(model, "enable_input_require_grads"):
        model.enable_input_require_grads()
    model.print_trainable_parameters()

    raw_data = load_dataset("json", data_files={"train": error_dataset_path})["train"]

    def tokenize_function(examples):
        batch_inputs = []
        batch_labels = []
        for wrong, gt in zip(examples["wrong_response"], examples["ground_truth_response"]):
            # Use chat template for both input and output, disable thinking
            messages = [
                {"role": "user", "content": 
                f"""
                You are a Knowledge Graph Specialist responsible for extracting entities and relationships from the input text.
                Your task is to fix the incorrect format of given entity extraction output.
                Format requirements:
                Entities: There should be a total of 4 fields for each entity, delimited by `<|#|>`, on a single line.
                The first field *must* be the literal string `entity`.
                Format: `entity<|#|>entity_name<|#|>entity_type<|#|>entity_description`\n
                Relationships: Output a total of 5 fields for each relationship, delimited by `<|#|>`, on a single line.
                The first field *must* be the literal string `relation`.
                Format: `relation<|#|>source_entity<|#|>target_entity<|#|>relationship_keywords<|#|>relationship_description`\n
                Here is an entity extraction output with wrong format:\n
                {wrong}\n 
                Fixed output:
                """},
                {"role": "assistant", "content": gt}
            ]
            input_ids = tokenizer.apply_chat_template(
                messages,
                truncation=True,
                max_length=max_length,
                add_generation_prompt=False,
                enable_thinking=False,
                padding=False
            )
            # Mask everything before assistant
            assistant_token_ids = tokenizer.encode("<|im_start|>assistant", add_special_tokens=False)
            newline_token = tokenizer.encode("\n", add_special_tokens=False)[0]
            assistant_start_index = -1
            for i in range(len(input_ids) - len(assistant_token_ids)):
                if input_ids[i:i + len(assistant_token_ids)] == assistant_token_ids:
                    try:
                        assistant_start_index = input_ids.index(newline_token, i) + 1
                        break
                    except ValueError:
                        pass
            if assistant_start_index != -1:
                labels = [-100] * assistant_start_index + input_ids[assistant_start_index:]
            else:
                labels = [-100] * len(input_ids)
            batch_inputs.append(input_ids)
            batch_labels.append(labels)
        return {"input_ids": batch_inputs, "labels": batch_labels}

    tokenized_dataset = raw_data.map(tokenize_function, batched=True, remove_columns=raw_data.column_names)

    from transformers import DataCollatorForSeq2Seq
    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        pad_to_multiple_of=8,
        label_pad_token_id=-100,
        return_tensors="pt"
    )

    run_name = f"{model_name}_format_error_{datetime.now().strftime('%m-%d_%H-%M-%S')}"
    logging_dir = os.path.join('./tf-logs', run_name)

    training_args = TrainingArguments(
        output_dir="./results",
        per_device_train_batch_size=batch_size,
        num_train_epochs=1,
        logging_dir=logging_dir,
        logging_steps=10,
        save_strategy="epoch",
        learning_rate=1e-5,
        fp16=torch.cuda.is_available(),
        report_to="tensorboard",
        gradient_checkpointing=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
        data_collator=data_collator,
    )

    trainer.train()
    trainer.save_model(f"./finetuned-{model_name}-format-error-lora")
    tokenizer.save_pretrained(f"./finetuned-{model_name}-format-error-lora")
    print(f"Model and tokenizer saved to ./finetuned-{model_name}-format-error-lora")

if __name__ == "__main__":
    load_dotenv(dotenv_path=".env", override=True)
    finetune_format_error("Qwen3-4B", os.getenv("PATH_QWEN_4B"), "./incorrect_correct_dataset/format_error_pairs_200_train.json", batch_size=1, max_length=2048)
    finetune_format_error("Qwen3-8B", os.getenv("PATH_QWEN_8B"), "./incorrect_correct_dataset/format_error_pairs_200_train.json", batch_size=1, max_length=2048)